name: CI/CD Pipeline
# The dynamic name for each run of the workflow
run-name: CI/CD on ${{ github.ref_name }} triggered by @${{ github.actor }}

on:
  push:
    branches: [ dev, main, week5]
  pull_request:
    branches: [ dev, main]

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          # Ensure req.txt includes scikit-learn and matplotlib
          pip install -r req.txt pytest pandera scikit-learn pandas matplotlib mlflow seaborn google-cloud-storage

      - name: Authenticate to Google Cloud
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configure DVC and Pull Data
        run: |
          dvc remote default gcsremote
          dvc pull
      
      - name: Run data validation Tests and Evaluate latest model from gcs bucket, stored by mlflow
        # This single command now runs tests AND creates report files if tests pass
        run: pytest tests/test_evaluation_1.py

      - name: Generate Timestamp
        id: timestamp
        run: echo "TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV

      - name: Setup CML
        uses: iterative/setup-cml@v2
      - name: Comment test results with CML
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml comment create cml_report.md
      - name: Upload Report Artifacts to GCS
        if: success()
        run: |
          #  Save the report to GCS bucket
          gcloud storage cp cml_report.md confusion_matrix.png gs://mlops-week02-ga02-electric-wave-472614-d5/reports/${{ github.ref_name }}-${{ env.TIMESTAMP }}/

